### ISSUE TITLE
Cheat mistakes Sapper as being a weapon and cannot sap sentries

### ISSUE THREAD

**Issue by sumdudinhell** [8dcc/tf2-cheat#17] opened 2024-01-25 00:29 UTC
Basically the cheat confuses the sapper as being a weapon, so if you're in a area full of enemies you won't be able to sap the sentry. I modified the source code a little to detect when the player is holding a sapper, and that fixed it. However, it's still an issue since other people don't have the same fix

**Comment by 8dcc** [comment] 2024-01-25 01:22
I think the problem is that I am only checking for the weapon slot:

https://github.com/8dcc/tf2-cheat/blob/c1be8835ac25e5519e2e01dc8b8225f4c0d45a97/src/features/aim/aimbot.c#L129-L133

I didn't think about the sapper. I will add a fix as soon as possible.

**Comment by 8dcc** [comment] 2024-01-28 01:01
Fixed in b5ca2a40069a55ea9d66a9419169cc7477b9fc51.

**Closed by 8dcc** 2024-01-28 01:01 UTC
Labels: good first issue

**Comment by sumdudinhell** [comment] 2024-01-28 02:06
thanks!
